### ISSUE TITLE
No output for GIMX Dualshock 3 firmware (and probably the others)

### ISSUE THREAD

**Issue by techsrus** [isage/vixen-helper#4]
Trying to connect my [GIMX](http://blog.gimx.fr/) adapter to Vita using their DS3 firmware and it should've worked as it spoofs as a genuine DS3, but it didn't. Tried feeding it through vixen-helper but the output was empty.

[lsusb.txt](https://github.com/user-attachments/files/17540206/lsusb.txt)
Here is the vita-lsusb dump using the DS3 firmware

**Comment by isage** [comment]
vixen-helper won't work because system ds3 driver intercepts it.

**Comment by techsrus** [comment]
Wait, I'm an idiot, I forgot there was a ds3 version of vixen. It's working.
